services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - NODE_NO_WARNINGS=1
    command: pnpm test  # Only run tests, like CI

  generate-issues:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - NODE_NO_WARNINGS=1
      - GH_PAT=${GH_PAT}
    command: pnpm run create-issues  # Only run issue generation, like CI 