services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./coverage:/app/coverage
      - ./project-briefs:/app/project-briefs
      - ./local-issues:/app/local-issues
    environment:
      - NODE_ENV=test
      - NODE_NO_WARNINGS=1
      - GH_PAT=${GH_PAT}  # This will use the local GH_PAT if set
    command: sh -c "pnpm test && pnpm run create-issues"  # Run both test and issue generation like CI 