name: Generate Issues from Brief

on:
  workflow_dispatch:
  push:
    paths:
      - "project-briefs/*.md"

jobs:
  parse-and-create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Issue Generator
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          NODE_NO_WARNINGS: 1
        run: node --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));' src/scripts/create-issues-from-brief.mts
